# Generated by Django 6.0.1 on 2026-01-17 14:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invmngr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='inventorymodel',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='purchaseordermodel',
            options={'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='suppliermodel',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='transactionmodel',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='warehousemodel',
            options={'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.CreateModel(
            name='InviteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('A', 'Admin'), ('S', 'Staff'), ('V', 'Viewer')], max_length=1)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('E', 'Expired'), ('R', 'Revoked')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('warehouses', models.ManyToManyField(blank=True, related_name='invites', to='invmngr.warehousemodel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='invmngr_inv_email_806eb4_idx'), models.Index(fields=['token'], name='invmngr_inv_token_628f55_idx'), models.Index(fields=['status'], name='invmngr_inv_status_901586_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'P')), fields=('email',), name='unique_pending_invite_per_email')],
            },
        ),
    ]
